FROM acrfabricinference.azurecr.io/fabric/control-plane@sha256:4b1ee65a6c3317a955c8e061d4c4f40b1575c5b328f6fffb8ef9b0edf7ee07c8
COPY --chown=65532:65532 api/v1/deployments.py /opt/venv/lib/python3.12/site-packages/app/api/v1/deployments.py
