import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowLeftIcon, BoxIcon, ExternalLinkIcon, Trash2Icon } from "lucide-react"

import { deleteDeployment } from "@/app/(console)/actions"
import { PageContainer, PageHeader } from "@/components/console/page-header"
import { StatusBadge } from "@/components/console/status-badge"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { getDeployment, getDeploymentStatuses, getDeploymentUsage, listPlacements } from "@/lib/fabric/data"
import { getConsoleContext, hasScope } from "@/lib/fabric/session"
import { formatDate, formatNumber, formatRelative, shortId } from "@/lib/format"

export default async function DeploymentDetailPage({ params, searchParams }: PageProps<"/deployments/[deploymentId]">) {
  const { deploymentId } = await params
  const query = await searchParams
  const [context, deployment] = await Promise.all([getConsoleContext(), getDeployment(deploymentId)])
  if (!deployment) notFound()
  const [placements, statuses, usage] = await Promise.all([listPlacements(deploymentId), getDeploymentStatuses(deploymentId), getDeploymentUsage(deploymentId)])
  const canWrite = hasScope(context, "deployments:write") && !context.demo
  const deleteAction = deleteDeployment.bind(null, deployment.id)

  return <PageContainer><PageHeader title={deployment.name} description={`${deployment.model_alias} · Generation ${deployment.generation}`} actions={<><Button variant="outline" render={<Link href="/deployments" />}><ArrowLeftIcon /> All deployments</Button><form action={deleteAction}><Button type="submit" variant="destructive" disabled={!canWrite}><Trash2Icon /> Delete</Button></form></>}><div className="flex items-center gap-2 pt-1"><StatusBadge status={deployment.status} /><span className="text-xs text-muted-foreground">Updated {formatRelative(deployment.updated_at)}</span></div></PageHeader>
    {query.placement === "failed" ? <Alert><BoxIcon /><AlertTitle>Deployment created without a placement</AlertTitle><AlertDescription>No compatible stamp was available. The desired state is saved; connect capacity and assign it when ready.</AlertDescription></Alert> : null}
    <Tabs defaultValue="overview"><TabsList variant="line"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="placements">Placements</TabsTrigger><TabsTrigger value="status">Status</TabsTrigger><TabsTrigger value="usage">Usage</TabsTrigger><TabsTrigger value="configuration">Configuration</TabsTrigger></TabsList>
      <TabsContent value="overview" className="pt-5"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[{ label: "Replicas", value: deployment.desired_spec.replicas }, { label: "GPU request", value: `${deployment.desired_spec.resources.gpu_count} × ${deployment.desired_spec.resources.gpu_class.toUpperCase()}` }, { label: "Placements", value: placements.length }, { label: "Inference events", value: formatNumber(usage.events) }].map((item) => <Card key={item.label}><CardHeader><CardDescription>{item.label}</CardDescription><CardTitle className="text-2xl tabular-nums">{item.value}</CardTitle></CardHeader></Card>)}</div><Card className="mt-5"><CardHeader><CardTitle>Runtime</CardTitle><CardDescription>Current desired configuration sent to assigned stamps.</CardDescription></CardHeader><CardContent><dl className="grid gap-5 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-muted-foreground">Release</dt><dd className="mt-1 font-mono">{deployment.desired_spec.runtime.release}</dd></div><div><dt className="text-muted-foreground">Kernel mode</dt><dd className="mt-1 capitalize">{deployment.desired_spec.runtime.kernel_mode}</dd></div><div><dt className="text-muted-foreground">Strategy</dt><dd className="mt-1">{deployment.desired_spec.runtime.strategy.replaceAll("_", " ")}</dd></div><div><dt className="text-muted-foreground">Created</dt><dd className="mt-1">{formatDate(deployment.created_at)}</dd></div></dl></CardContent></Card></TabsContent>
      <TabsContent value="placements" className="pt-5"><Card><CardHeader><CardTitle>Assigned stamps</CardTitle><CardDescription>Where the control plane has advertised this desired state.</CardDescription></CardHeader><CardContent className="px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">Stamp</TableHead><TableHead>Status</TableHead><TableHead>Desired generation</TableHead><TableHead className="pr-6">Observed generation</TableHead></TableRow></TableHeader><TableBody>{placements.map((item) => <TableRow key={item.id}><TableCell className="pl-6 font-mono text-xs">{shortId(item.stamp_id)}</TableCell><TableCell><StatusBadge status={item.status} /></TableCell><TableCell>{item.desired_generation}</TableCell><TableCell className="pr-6">{item.observed_generation ?? "Not reported"}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="status" className="pt-5">{statuses.length ? <div className="space-y-4">{statuses.map((status) => <Card key={status.stamp_id}><CardHeader><CardTitle className="flex items-center gap-2"><StatusBadge status={status.phase} /> <span className="font-mono text-xs font-normal text-muted-foreground">{shortId(status.stamp_id)}</span></CardTitle><CardDescription>Reported {formatRelative(status.reported_at)}</CardDescription></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-3"><div><div className="text-xs text-muted-foreground">Ready replicas</div><div className="mt-1 text-lg font-semibold">{status.ready_replicas}</div></div><div><div className="text-xs text-muted-foreground">Unavailable</div><div className="mt-1 text-lg font-semibold">{status.unavailable_replicas}</div></div><div><div className="text-xs text-muted-foreground">Observed generation</div><div className="mt-1 text-lg font-semibold">{status.observed_generation ?? "—"}</div></div></div>{status.endpoint ? <Button className="mt-5" variant="outline" render={<a href={status.endpoint} target="_blank" rel="noreferrer" />}>Open endpoint <ExternalLinkIcon /></Button> : null}</CardContent></Card>)}</div> : <Alert><BoxIcon /><AlertTitle>No status reported</AlertTitle><AlertDescription>A stamp has not reported a workload observation for this deployment yet.</AlertDescription></Alert>}</TabsContent>
      <TabsContent value="usage" className="pt-5"><div className="grid gap-5 md:grid-cols-3">{[{ label: "Requests", value: usage.events }, { label: "Input tokens", value: usage.input_tokens }, { label: "Output tokens", value: usage.output_tokens }].map((item) => <Card key={item.label}><CardHeader><CardDescription>{item.label}</CardDescription><CardTitle className="text-2xl">{formatNumber(item.value)}</CardTitle></CardHeader></Card>)}</div><Alert className="mt-5"><BoxIcon /><AlertTitle>Operational usage</AlertTitle><AlertDescription>Collector totals are deduplicated but are not billing-grade accounting.</AlertDescription></Alert></TabsContent>
      <TabsContent value="configuration" className="pt-5"><Card><CardHeader><CardTitle>Desired specification</CardTitle><CardDescription>The complete server-validated configuration for generation {deployment.generation}.</CardDescription></CardHeader><CardContent><pre className="overflow-auto rounded-lg border bg-muted/40 p-4 text-xs leading-6">{JSON.stringify(deployment.desired_spec, null, 2)}</pre></CardContent></Card></TabsContent>
    </Tabs>
  </PageContainer>
}
