import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowLeftIcon, BoxIcon } from "lucide-react"

import { LiveRefresh } from "@/components/console/live-refresh"
import { DeleteDeploymentDialog } from "@/components/console/resource-dialogs"
import { PageContainer, PageHeader } from "@/components/console/page-header"
import { StatusBadge } from "@/components/console/status-badge"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { getDeployment, getDeploymentStatuses, getDeploymentUsage, listPlacements, listStamps } from "@/lib/fabric/data"
import { deploymentState, statusReason } from "@/lib/fabric/resource-state"
import { getConsoleContext, hasScope } from "@/lib/fabric/session"
import { formatDate, formatNumber, formatRelative, shortId } from "@/lib/format"

export default async function DeploymentDetailPage({ params, searchParams }: PageProps<"/deployments/[deploymentId]">) {
  const { deploymentId } = await params
  const query = await searchParams
  const [context, deployment] = await Promise.all([getConsoleContext(), getDeployment(deploymentId)])
  if (!deployment) notFound()
  const [placementResult, statusResult, usageResult, stampResult] = await Promise.allSettled([listPlacements(deploymentId), getDeploymentStatuses(deploymentId), getDeploymentUsage(deploymentId), hasScope(context, "stamps:read") ? listStamps() : Promise.resolve(undefined)])
  const placements = placementResult.status === "fulfilled" ? placementResult.value : []
  const statuses = statusResult.status === "fulfilled" ? statusResult.value : []
  const usage = usageResult.status === "fulfilled" ? usageResult.value : null
  const stamps = stampResult.status === "fulfilled" ? stampResult.value : undefined
  const error = [placementResult, statusResult, usageResult, stampResult].some((item) => item.status === "rejected") ? "Some deployment data could not be checked." : null
  const state = deploymentState(deployment, statusResult.status === "fulfilled" ? statuses : undefined, placementResult.status === "fulfilled" ? placements : undefined, stamps)
  const checkedAt = new Date().toISOString()
  const canWrite = hasScope(context, "deployments:write")
  const deleting = ["terminating", "deleted"].includes(state.status)
  const requestedGpus = placements.filter((item) => !["terminating", "deleted", "revoked"].includes(item.status)).length * deployment.desired_spec.replicas * deployment.desired_spec.resources.gpu_count

  return <PageContainer><PageHeader title={deployment.name} description={`${deployment.model_alias} · Generation ${deployment.generation}`} actions={<><Button variant="outline" render={<Link href="/deployments" />}><ArrowLeftIcon /> All deployments</Button><DeleteDeploymentDialog deploymentId={deployment.id} name={deployment.name} modelAlias={deployment.model_alias} gpuCount={requestedGpus} gpuClass={deployment.desired_spec.resources.gpu_class} disabled={!canWrite || deleting} /></>}><div className="flex flex-wrap items-center gap-2 pt-1"><StatusBadge status={state.status} /><span className="text-xs text-muted-foreground">Updated {formatRelative(deployment.updated_at)}</span></div><p className="text-sm text-muted-foreground">{state.detail}</p></PageHeader>
    <LiveRefresh checkedAt={checkedAt} error={error} />
    {query.placement === "failed" ? <Alert><BoxIcon /><AlertTitle>Deployment created without a placement</AlertTitle><AlertDescription>No compatible stamp was available. The desired state is saved; connect capacity and assign it when ready.</AlertDescription></Alert> : null}
    <Tabs defaultValue="overview"><TabsList variant="line"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="placements">Placements</TabsTrigger><TabsTrigger value="status">Status</TabsTrigger><TabsTrigger value="usage">Usage</TabsTrigger><TabsTrigger value="configuration">Configuration</TabsTrigger></TabsList>
      <TabsContent value="overview" className="pt-5"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[{ label: "Observed ready replicas", value: `${state.readyReplicas ?? "—"} / ${state.desiredReplicas}` }, { label: "GPU request", value: `${deployment.desired_spec.resources.gpu_count} × ${deployment.desired_spec.resources.gpu_class.toUpperCase()}` }, { label: "Placements", value: placementResult.status === "fulfilled" ? placements.length : "Unavailable" }, { label: "Inference events", value: usage ? formatNumber(usage.events) : "Unavailable" }].map((item) => <Card key={item.label}><CardHeader><CardDescription>{item.label}</CardDescription><CardTitle className="text-2xl tabular-nums">{item.value}</CardTitle></CardHeader></Card>)}</div><Card className="mt-5"><CardHeader><CardTitle>Runtime</CardTitle><CardDescription>Current desired configuration sent to assigned stamps.</CardDescription></CardHeader><CardContent><dl className="grid gap-5 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-muted-foreground">Release</dt><dd className="mt-1 font-mono">{deployment.desired_spec.runtime.release}</dd></div><div><dt className="text-muted-foreground">Kernel mode</dt><dd className="mt-1 capitalize">{deployment.desired_spec.runtime.kernel_mode}</dd></div><div><dt className="text-muted-foreground">Strategy</dt><dd className="mt-1">{deployment.desired_spec.runtime.strategy.replaceAll("_", " ")}</dd></div><div><dt className="text-muted-foreground">Created</dt><dd className="mt-1">{formatDate(deployment.created_at)}</dd></div></dl></CardContent></Card></TabsContent>
      <TabsContent value="placements" className="pt-5"><Card><CardHeader><CardTitle>Assigned stamps</CardTitle><CardDescription>Placement generations are stamp delivery watermarks; they are independent of the deployment generation.</CardDescription></CardHeader><CardContent className="px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">Stamp</TableHead><TableHead>Status</TableHead><TableHead>Desired generation</TableHead><TableHead className="pr-6">Observed generation</TableHead></TableRow></TableHeader><TableBody>{placements.map((item) => <TableRow key={item.id}><TableCell className="pl-6 font-mono text-xs">{shortId(item.stamp_id)}</TableCell><TableCell><StatusBadge status={["terminating", "deleted", "revoked"].includes(item.status) ? item.status : deploymentState(deployment, statuses, [item], stamps).status} /></TableCell><TableCell>{item.desired_generation}</TableCell><TableCell className="pr-6">{item.observed_generation ?? "Not reported"}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="status" className="pt-5">{statuses.length ? <div className="space-y-4">{statuses.map((status) => <Card key={status.stamp_id}><CardHeader><CardTitle className="flex items-center gap-2"><StatusBadge status={["terminating", "deleted"].includes(status.phase) ? status.phase : deploymentState(deployment, [status], placements.filter((item) => item.stamp_id === status.stamp_id), stamps).status} /> <span className="font-mono text-xs font-normal text-muted-foreground">{shortId(status.stamp_id)}</span></CardTitle><CardDescription>Last workload observation {formatRelative(status.reported_at)} · reports update when workload state changes</CardDescription></CardHeader><CardContent>{statusReason(status) ? <p className="mb-5 text-sm text-muted-foreground">{statusReason(status)}</p> : null}<div className="grid gap-4 sm:grid-cols-3"><div><div className="text-xs text-muted-foreground">Ready replicas</div><div className="mt-1 text-lg font-semibold">{status.ready_replicas}</div></div><div><div className="text-xs text-muted-foreground">Unavailable</div><div className="mt-1 text-lg font-semibold">{status.unavailable_replicas}</div></div><div><div className="text-xs text-muted-foreground">Observed generation</div><div className="mt-1 text-lg font-semibold">{status.observed_generation ?? "—"}</div></div></div></CardContent></Card>)}</div> : <Alert><BoxIcon /><AlertTitle>{statusResult.status === "fulfilled" ? "No status reported" : "Status unavailable"}</AlertTitle><AlertDescription>{statusResult.status === "fulfilled" ? "A stamp has not reported a workload observation for this deployment yet." : "Refresh to check the workload observations again."}</AlertDescription></Alert>}</TabsContent>
      <TabsContent value="usage" className="pt-5"><div className="grid gap-5 md:grid-cols-3">{[{ label: "Requests", value: usage?.events }, { label: "Input tokens", value: usage?.input_tokens }, { label: "Output tokens", value: usage?.output_tokens }].map((item) => <Card key={item.label}><CardHeader><CardDescription>{item.label}</CardDescription><CardTitle className="text-2xl">{item.value === undefined ? "Unavailable" : formatNumber(item.value)}</CardTitle></CardHeader></Card>)}</div><Alert className="mt-5"><BoxIcon /><AlertTitle>Operational usage</AlertTitle><AlertDescription>Collector totals are deduplicated but are not billing-grade accounting.</AlertDescription></Alert></TabsContent>
      <TabsContent value="configuration" className="pt-5"><Card><CardHeader><CardTitle>Desired specification</CardTitle><CardDescription>The complete server-validated configuration for generation {deployment.generation}.</CardDescription></CardHeader><CardContent><pre className="overflow-auto rounded-lg border bg-muted/40 p-4 text-xs leading-6">{JSON.stringify(deployment.desired_spec, null, 2)}</pre></CardContent></Card></TabsContent>
    </Tabs>
  </PageContainer>
}
